id: I8A856445
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:41:57+00:00'
last_modified: '2022-06-08T09:20:34.330532+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7958
  title: གསུང་འབུམ། བློ་གྲོས་བཟང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5A49:
      image_group_id: I1KG9590
      title: ''
      total_pages: 544
      order: 1
      base_file: 5A49.txt
    A98B:
      image_group_id: I1KG9591
      title: ''
      total_pages: 491
      order: 2
      base_file: A98B.txt
    78B0:
      image_group_id: I1KG9592
      title: ''
      total_pages: 631
      order: 3
      base_file: 78B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
